// <auto-generated>
// UI-P2: generated from std/UI/Core/Themes/Light.arml + Dark.arml.
// Do not edit by hand. Regenerate:
//   UPDATE_BUILTIN_THEME=1 cargo test -p arc-ui --test design_tokens_contract -- builtin_theme_colors_g_as_in_sync
// </auto-generated>

namespace Arc.UI.Styling;

using Arc.UI.Media;

/// <summary>内置 Light/Dark 色值填充（ARML 编译期扁平产物）。</summary>
internal class BuiltInThemeColors {
    /// <summary>从 `std/UI/Core/Themes/Light.arml` 生成的色值注册（勿手改；改 Themes/*.arml 后再生）。</summary>
    public static void FillLightColors(ResourceDictionary d) {
        d.Add(BuiltInTheme.Background, ResourceValue.Brush(Brushes.Parse("#FFF5F5F5")));
        d.Add(BuiltInTheme.Surface, ResourceValue.Brush(Brushes.Parse("#FFFFFFFF")));
        d.Add(BuiltInTheme.Border, ResourceValue.Brush(Brushes.Parse("#FFD9D9D9")));
        d.Add(BuiltInTheme.BorderDisabled, ResourceValue.Brush(Brushes.Parse("#FFD9D9D9")));
        d.Add(BuiltInTheme.TextPrimary, ResourceValue.Brush(Brushes.Parse("#E0000000")));
        d.Add(BuiltInTheme.TextSecondary, ResourceValue.Brush(Brushes.Parse("#A6000000")));
        d.Add(BuiltInTheme.Primary, ResourceValue.Brush(Brushes.Parse("#FF1677FF")));
        d.Add(BuiltInTheme.PrimaryHover, ResourceValue.Brush(Brushes.Parse("#FF4096FF")));
        d.Add(BuiltInTheme.PrimaryPressed, ResourceValue.Brush(Brushes.Parse("#FF0958D9")));
        d.Add(BuiltInTheme.FocusRing, ResourceValue.Brush(Brushes.Parse("#661677FF")));
        d.Add(BuiltInTheme.DisabledFill, ResourceValue.Brush(Brushes.Parse("#FFF5F5F5")));
        d.Add(BuiltInTheme.DisabledText, ResourceValue.Brush(Brushes.Parse("#FFBFBFBF")));
        d.Add(BuiltInTheme.TextOnAccent, ResourceValue.Brush(Brushes.Parse("#FFFFFFFF")));
        d.Add(BuiltInTheme.TextPlaceholder, ResourceValue.Brush(Brushes.Parse("#FFBFBFBF")));
        d.Add(BuiltInTheme.Transparent, ResourceValue.Brush(Brushes.Parse("#00000000")));
        d.Add(BuiltInTheme.SurfaceHover, ResourceValue.Brush(Brushes.Parse("#FFE6F4FF")));
        d.Add(BuiltInTheme.SurfaceStripe, ResourceValue.Brush(Brushes.Parse("#FFFAFAFA")));
        d.Add(BuiltInTheme.SliderTrack, ResourceValue.Brush(Brushes.Parse("#FFF0F0F0")));
        d.Add(BuiltInTheme.ScrollTrack, ResourceValue.Brush(Brushes.Parse("#FFF5F5F5")));
        d.Add(BuiltInTheme.ScrollThumb, ResourceValue.Brush(Brushes.Parse("#FFBFBFBF")));
        d.Add(BuiltInTheme.ScrollThumbHover, ResourceValue.Brush(Brushes.Parse("#FF8C8C8C")));
        d.Add(BuiltInTheme.ScrollThumbPressed, ResourceValue.Brush(Brushes.Parse("#FF595959")));
        d.Add(BuiltInTheme.Overlay, ResourceValue.Brush(Brushes.Parse("#73000000")));
        d.Add(BuiltInTheme.Danger, ResourceValue.Brush(Brushes.Parse("#FFFF4D4F")));
        d.Add(BuiltInTheme.DangerHover, ResourceValue.Brush(Brushes.Parse("#FFFF7875")));
        d.Add(BuiltInTheme.DangerPressed, ResourceValue.Brush(Brushes.Parse("#FFD9363E")));
        d.Add(BuiltInTheme.Success, ResourceValue.Brush(Brushes.Parse("#FF52C41A")));
        d.Add(BuiltInTheme.Warning, ResourceValue.Brush(Brushes.Parse("#FFFAAD14")));
        d.Add(BuiltInTheme.TextSelection, ResourceValue.Brush(Brushes.Parse("#401677FF")));
        d.Add(BuiltInTheme.ImageFill, ResourceValue.Brush(Brushes.Parse("#FFD0D0D0")));
        d.Add(BuiltInTheme.ImageBorder, ResourceValue.Brush(Brushes.Parse("#FF606060")));
        d.Add(BuiltInTheme.TextHighlight, ResourceValue.Brush(Brushes.Parse("#FFF4C2")));
    }

    /// <summary>从 `std/UI/Core/Themes/Dark.arml` 生成的色值注册（勿手改；改 Themes/*.arml 后再生）。</summary>
    public static void FillDarkColors(ResourceDictionary d) {
        d.Add(BuiltInTheme.Background, ResourceValue.Brush(Brushes.Parse("#FF000000")));
        d.Add(BuiltInTheme.Surface, ResourceValue.Brush(Brushes.Parse("#FF141414")));
        d.Add(BuiltInTheme.Border, ResourceValue.Brush(Brushes.Parse("#FF424242")));
        d.Add(BuiltInTheme.BorderDisabled, ResourceValue.Brush(Brushes.Parse("#FF424242")));
        d.Add(BuiltInTheme.TextPrimary, ResourceValue.Brush(Brushes.Parse("#D9FFFFFF")));
        d.Add(BuiltInTheme.TextSecondary, ResourceValue.Brush(Brushes.Parse("#A6FFFFFF")));
        d.Add(BuiltInTheme.Primary, ResourceValue.Brush(Brushes.Parse("#FF1668DC")));
        d.Add(BuiltInTheme.PrimaryHover, ResourceValue.Brush(Brushes.Parse("#FF3C89E8")));
        d.Add(BuiltInTheme.PrimaryPressed, ResourceValue.Brush(Brushes.Parse("#FF1554AD")));
        d.Add(BuiltInTheme.FocusRing, ResourceValue.Brush(Brushes.Parse("#661668DC")));
        d.Add(BuiltInTheme.DisabledFill, ResourceValue.Brush(Brushes.Parse("#FF1F1F1F")));
        d.Add(BuiltInTheme.DisabledText, ResourceValue.Brush(Brushes.Parse("#FF595959")));
        d.Add(BuiltInTheme.TextOnAccent, ResourceValue.Brush(Brushes.Parse("#FFFFFFFF")));
        d.Add(BuiltInTheme.TextPlaceholder, ResourceValue.Brush(Brushes.Parse("#FF595959")));
        d.Add(BuiltInTheme.Transparent, ResourceValue.Brush(Brushes.Parse("#00000000")));
        d.Add(BuiltInTheme.SurfaceHover, ResourceValue.Brush(Brushes.Parse("#FF111A2C")));
        d.Add(BuiltInTheme.SurfaceStripe, ResourceValue.Brush(Brushes.Parse("#FF1F1F1F")));
        d.Add(BuiltInTheme.SliderTrack, ResourceValue.Brush(Brushes.Parse("#FF303030")));
        d.Add(BuiltInTheme.ScrollTrack, ResourceValue.Brush(Brushes.Parse("#FF1F1F1F")));
        d.Add(BuiltInTheme.ScrollThumb, ResourceValue.Brush(Brushes.Parse("#FF595959")));
        d.Add(BuiltInTheme.ScrollThumbHover, ResourceValue.Brush(Brushes.Parse("#FF8C8C8C")));
        d.Add(BuiltInTheme.ScrollThumbPressed, ResourceValue.Brush(Brushes.Parse("#FFBFBFBF")));
        d.Add(BuiltInTheme.Overlay, ResourceValue.Brush(Brushes.Parse("#73000000")));
        d.Add(BuiltInTheme.Danger, ResourceValue.Brush(Brushes.Parse("#FFDC4446")));
        d.Add(BuiltInTheme.DangerHover, ResourceValue.Brush(Brushes.Parse("#FFE86E6B")));
        d.Add(BuiltInTheme.DangerPressed, ResourceValue.Brush(Brushes.Parse("#FFAD3030")));
        d.Add(BuiltInTheme.Success, ResourceValue.Brush(Brushes.Parse("#FF49AA19")));
        d.Add(BuiltInTheme.Warning, ResourceValue.Brush(Brushes.Parse("#FFD89614")));
        d.Add(BuiltInTheme.TextSelection, ResourceValue.Brush(Brushes.Parse("#401668DC")));
        d.Add(BuiltInTheme.ImageFill, ResourceValue.Brush(Brushes.Parse("#FF303030")));
        d.Add(BuiltInTheme.ImageBorder, ResourceValue.Brush(Brushes.Parse("#FF8C8C8C")));
        d.Add(BuiltInTheme.TextHighlight, ResourceValue.Brush(Brushes.Parse("#FF5C4B1F")));
    }
}
