// <auto-generated>
// UI-P2: generated from std/UI/Core/Themes/Light.arml + Dark.arml.
// Do not edit by hand. Regenerate:
//   UPDATE_BUILTIN_THEME=1 cargo test -p arc-ui --test design_tokens_contract -- builtin_theme_colors_g_as_in_sync
// </auto-generated>

namespace Arc.UI.Styling;

using Arc.UI.Media;

/// <summary>内置 Light/Dark 色值填充（ARML 编译期扁平产物）。</summary>
internal class BuiltInThemeColors {
    /// <summary>从 `std/UI/Core/Themes/Light.arml` 生成的色值注册（勿手改；改 Themes/*.arml 后再生）。</summary>
    public static void FillLightColors(ResourceDictionary d) {
        d.Add(BuiltInTheme.Background, ResourceValue.Brush(Brushes.Parse("#FFFAFAFA")));
        d.Add(BuiltInTheme.Surface, ResourceValue.Brush(Brushes.Parse("#FFFFFFFF")));
        d.Add(BuiltInTheme.Border, ResourceValue.Brush(Brushes.Parse("#FFE6E6EC")));
        d.Add(BuiltInTheme.TextPrimary, ResourceValue.Brush(Brushes.Parse("#FF1A1A1A")));
        d.Add(BuiltInTheme.TextSecondary, ResourceValue.Brush(Brushes.Parse("#FF8A8A93")));
        d.Add(BuiltInTheme.Primary, ResourceValue.Brush(Brushes.Parse("#FF4F46E5")));
        d.Add(BuiltInTheme.PrimaryHover, ResourceValue.Brush(Brushes.Parse("#FF6366F1")));
        d.Add(BuiltInTheme.PrimaryPressed, ResourceValue.Brush(Brushes.Parse("#FF4338CA")));
        d.Add(BuiltInTheme.FocusRing, ResourceValue.Brush(Brushes.Parse("#734F46E5")));
        d.Add(BuiltInTheme.DisabledFill, ResourceValue.Brush(Brushes.Parse("#FFF3F3F6")));
        d.Add(BuiltInTheme.DisabledText, ResourceValue.Brush(Brushes.Parse("#FFB8B8C0")));
        d.Add(BuiltInTheme.TextOnAccent, ResourceValue.Brush(Brushes.Parse("#FFFFFFFF")));
        d.Add(BuiltInTheme.Transparent, ResourceValue.Brush(Brushes.Parse("#00000000")));
        d.Add(BuiltInTheme.SurfaceHover, ResourceValue.Brush(Brushes.Parse("#FFF4F4FF")));
        d.Add(BuiltInTheme.SurfaceStripe, ResourceValue.Brush(Brushes.Parse("#FFF7F7FA")));
        d.Add(BuiltInTheme.SliderTrack, ResourceValue.Brush(Brushes.Parse("#FFE0E0E6")));
        d.Add(BuiltInTheme.ScrollTrack, ResourceValue.Brush(Brushes.Parse("#FFF0F0F0")));
        d.Add(BuiltInTheme.ScrollThumb, ResourceValue.Brush(Brushes.Parse("#FF8A8A93")));
        d.Add(BuiltInTheme.ScrollThumbHover, ResourceValue.Brush(Brushes.Parse("#FF6E6E7A")));
        d.Add(BuiltInTheme.ScrollThumbActive, ResourceValue.Brush(Brushes.Parse("#FF4A4A55")));
        d.Add(BuiltInTheme.Placeholder, ResourceValue.Brush(Brushes.Parse("#FFB0B0BA")));
        d.Add(BuiltInTheme.Overlay, ResourceValue.Brush(Brushes.Parse("#661A1A1A")));
        d.Add(BuiltInTheme.Negative, ResourceValue.Brush(Brushes.Parse("#FFEF4444")));
        d.Add(BuiltInTheme.AccentGradientA, ResourceValue.Brush(Brushes.Parse("#FF4F46E5")));
        d.Add(BuiltInTheme.AccentGradientB, ResourceValue.Brush(Brushes.Parse("#FF7C3AED")));
    }

    /// <summary>从 `std/UI/Core/Themes/Dark.arml` 生成的色值注册（勿手改；改 Themes/*.arml 后再生）。</summary>
    public static void FillDarkColors(ResourceDictionary d) {
        d.Add(BuiltInTheme.Background, ResourceValue.Brush(Brushes.Parse("#FF0F0F12")));
        d.Add(BuiltInTheme.Surface, ResourceValue.Brush(Brushes.Parse("#FF17171C")));
        d.Add(BuiltInTheme.Border, ResourceValue.Brush(Brushes.Parse("#FF2A2A33")));
        d.Add(BuiltInTheme.TextPrimary, ResourceValue.Brush(Brushes.Parse("#FFF3F3F7")));
        d.Add(BuiltInTheme.TextSecondary, ResourceValue.Brush(Brushes.Parse("#FF9C9CA8")));
        d.Add(BuiltInTheme.Primary, ResourceValue.Brush(Brushes.Parse("#FF6366F1")));
        d.Add(BuiltInTheme.PrimaryHover, ResourceValue.Brush(Brushes.Parse("#FF818CF8")));
        d.Add(BuiltInTheme.PrimaryPressed, ResourceValue.Brush(Brushes.Parse("#FF4F46E5")));
        d.Add(BuiltInTheme.FocusRing, ResourceValue.Brush(Brushes.Parse("#8C6366F1")));
        d.Add(BuiltInTheme.DisabledFill, ResourceValue.Brush(Brushes.Parse("#FF23232A")));
        d.Add(BuiltInTheme.DisabledText, ResourceValue.Brush(Brushes.Parse("#FF5A5A66")));
        d.Add(BuiltInTheme.TextOnAccent, ResourceValue.Brush(Brushes.Parse("#FFFFFFFF")));
        d.Add(BuiltInTheme.Transparent, ResourceValue.Brush(Brushes.Parse("#00000000")));
        d.Add(BuiltInTheme.SurfaceHover, ResourceValue.Brush(Brushes.Parse("#FF222229")));
        d.Add(BuiltInTheme.SurfaceStripe, ResourceValue.Brush(Brushes.Parse("#FF1D1D24")));
        d.Add(BuiltInTheme.SliderTrack, ResourceValue.Brush(Brushes.Parse("#FF2E2E38")));
        d.Add(BuiltInTheme.ScrollTrack, ResourceValue.Brush(Brushes.Parse("#FF1A1A20")));
        d.Add(BuiltInTheme.ScrollThumb, ResourceValue.Brush(Brushes.Parse("#FF5A5A66")));
        d.Add(BuiltInTheme.ScrollThumbHover, ResourceValue.Brush(Brushes.Parse("#FF7A7A88")));
        d.Add(BuiltInTheme.ScrollThumbActive, ResourceValue.Brush(Brushes.Parse("#FF9A9AA8")));
        d.Add(BuiltInTheme.Placeholder, ResourceValue.Brush(Brushes.Parse("#FF6E6E7A")));
        d.Add(BuiltInTheme.Overlay, ResourceValue.Brush(Brushes.Parse("#8C000000")));
        d.Add(BuiltInTheme.Negative, ResourceValue.Brush(Brushes.Parse("#FFF87171")));
        d.Add(BuiltInTheme.AccentGradientA, ResourceValue.Brush(Brushes.Parse("#FF6366F1")));
        d.Add(BuiltInTheme.AccentGradientB, ResourceValue.Brush(Brushes.Parse("#FF8B5CF6")));
    }
}
