[package]
name = "Arc.Agent.Harness.Coding"
edition = "1"
version = "0.1.0"
kind = "library"
namespace = "Arc.Agent.Harness.Coding"

[dependencies]
Arc = { path = "../../Arc" }
"Arc.Agent" = { path = "../Agent" }
"Arc.Agent.Harness" = { path = "../Agent.Harness" }
